DEFAULT_REQUEST_HEADERS = {'Content-type': 'application/xml'}
MENU_ETA = 'eta'
MENU_API = 'api'
VALUE_VERSION = '@version'
ETA_MEN = "eta"
MENU = "menu"
FUB = "fub"
VALUE_MEN = "value"
STR_VAL = "@strValue"
UNIT = "@unit"
NAME = "@name"
URI = "@uri"
MENU_EP = "/user/menu"
DEC_PLACES = "@decPlaces"
SCALE_FACTOR = "@scaleFactor"
TEXT_OFFSET = "@advTextOffset"
OBJECT_VAL = "object"
XML_TEXT = "#text"
